add jpeg to develop
CherkashinDU/Modul_4_Task_1 pull request #1
Opened 2021-04-13 17:46 UTC by CherkashinDU

2021-04-13 18:44 UTC, MarinaRybalko commented
- Связь Employee -> Department принципиально построена неправильно. Сейчас у тебя получается что 1 сотрудник может работать в нескольких отделах, НО в отделе может быть ТОЛЬКО 1 сотрудник. В реальной жизни так не бывает) Бывает наоборот)
![image](https://user-images.githubusercontent.com/35547726/114601082-c3943280-9c9d-11eb-8ff7-9dcb9a7c9a06.png)

-Позиция бывает у сотрудника, но не у отдела.
![image](https://user-images.githubusercontent.com/35547726/114601375-1bcb3480-9c9e-11eb-8b12-cca2e3bd4324.png)

- Ты создал таблицу Зарплата. Но зарплата это как правило вычисляемое поле которое считается как HourlyRate * Hours. Не усложняй себе жизнь и просто добавь в таблицу Employee поле HourlyRate
![image](https://user-images.githubusercontent.com/35547726/114603848-e116cb80-9ca0-11eb-9217-2d9d1d166f07.png)

2021-04-13 18:44 UTC, MarinaRybalko requested changes
Немного поправить связи надо)

2021-04-13 19:19 UTC, CherkashinDU commented
Добавил изменные файлы: All, Department, Employee. Удалил  Salary.

2021-04-16 21:39 UTC, MarinaRybalko commented
Perfect!

2021-04-16 21:39 UTC, merged